// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMEYs0SYwG_XwgTZAhb7dB2dBSIMfMPTQ',
    appId: '1:88837761756:web:86e6c4072503163006e219',
    messagingSenderId: '88837761756',
    projectId: 'signindemo-a2a89',
    authDomain: 'signindemo-a2a89.firebaseapp.com',
    storageBucket: 'signindemo-a2a89.firebasestorage.app',
    measurementId: 'G-2ZLE0CWJ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06-y_Q5SKtRsB47mOAcyVmjxzLhvfWyc',
    appId: '1:88837761756:android:f8666d94aa3c576c06e219',
    messagingSenderId: '88837761756',
    projectId: 'signindemo-a2a89',
    storageBucket: 'signindemo-a2a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcnl9EsxR09e4H3ZhKSbPpWiRp2dy96ZM',
    appId: '1:88837761756:ios:e1626bebafb5325306e219',
    messagingSenderId: '88837761756',
    projectId: 'signindemo-a2a89',
    storageBucket: 'signindemo-a2a89.firebasestorage.app',
    iosBundleId: 'com.example.signinDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcnl9EsxR09e4H3ZhKSbPpWiRp2dy96ZM',
    appId: '1:88837761756:ios:e1626bebafb5325306e219',
    messagingSenderId: '88837761756',
    projectId: 'signindemo-a2a89',
    storageBucket: 'signindemo-a2a89.firebasestorage.app',
    iosBundleId: 'com.example.signinDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMEYs0SYwG_XwgTZAhb7dB2dBSIMfMPTQ',
    appId: '1:88837761756:web:58adcc4f2084476006e219',
    messagingSenderId: '88837761756',
    projectId: 'signindemo-a2a89',
    authDomain: 'signindemo-a2a89.firebaseapp.com',
    storageBucket: 'signindemo-a2a89.firebasestorage.app',
    measurementId: 'G-VXHKS58SF7',
  );
}
